apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  {{- range $index, $element := .Values.services }}
    - name: {{ $element.name }}
      port: {{ $element.port }}
      targetPort: {{ $element.targetPort }}
      protocol: TCP
  {{- end }}
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
