/*
Pets API

Testing DogsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sdk

import (
	"context"
	"testing"

	openapiclient "github.com/edenreich/definition-driven-development"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_sdk_DogsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DogsAPIService GetDogs", func(t *testing.T) {

		// t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DogsAPI.GetDogs(context.Background()).Execute()

		id1 := "7448d5c9-4e3a-4500-a018-fc25763dd3a4"
		id2 := "7448d5c9-4e3a-4500-a018-fc25763dd3a5"
		expected := []openapiclient.Dog{
			{
				Id:    &id1,
				Name:  "Fido",
				Breed: "Labrador",
				Age:   3,
			},
			{
				Id:    &id2,
				Name:  "Sparky",
				Breed: "Labrador",
				Age:   2,
			},
		}

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
		assert.Equal(t, expected, resp)
	})

}
