/*
 * Cat API
 *
 * A simple API to manage cats
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DefaultAPIService is a service that implements the logic for the DefaultAPIServicer
// This service should implement the business logic for every endpoint for the DefaultAPI API.
// Include any external packages or services that will be required by this service.
type DefaultAPIService struct {
}

// NewDefaultAPIService creates a default api service
func NewDefaultAPIService() DefaultAPIServicer {
	return &DefaultAPIService{}
}

// CatsGet - Get a list of all cats
func (s *DefaultAPIService) CatsGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update CatsGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Cat{}) or use other options such as http.Ok ...
	// return Response(200, []Cat{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CatsGet method not implemented")
}

// CatsIdGet - Get information about a specific cat
func (s *DefaultAPIService) CatsIdGet(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update CatsIdGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CatsIdGet method not implemented")
}

// CatsIdPut - Update information about a specific cat
func (s *DefaultAPIService) CatsIdPut(ctx context.Context, id string, cat Cat) (ImplResponse, error) {
	// TODO - update CatsIdPut with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CatsIdPut method not implemented")
}

// CatsPost - Create a new cat
func (s *DefaultAPIService) CatsPost(ctx context.Context, createdCat CreatedCat) (ImplResponse, error) {
	// TODO - update CatsPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	// return Response(201, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CatsPost method not implemented")
}
