//
//Pets API
//
//A simple API to manage pets
//
//The version of the OpenAPI document: 1.0.0
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: models/cat.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,3355,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,3373707,opt,name=name,proto3" json:"name,omitempty"`
	Breed string `protobuf:"bytes,94001524,opt,name=breed,proto3" json:"breed,omitempty"`
	Age   int32  `protobuf:"varint,96511,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *Cat) Reset() {
	*x = Cat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_cat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cat) ProtoMessage() {}

func (x *Cat) ProtoReflect() protoreflect.Message {
	mi := &file_models_cat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cat.ProtoReflect.Descriptor instead.
func (*Cat) Descriptor() ([]byte, []int) {
	return file_models_cat_proto_rawDescGZIP(), []int{0}
}

func (x *Cat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cat) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *Cat) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_models_cat_proto protoreflect.FileDescriptor

var file_models_cat_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x63, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x5a, 0x0a, 0x03, 0x43, 0x61, 0x74, 0x12,
	0x0f, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x9b, 0x1a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x15, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x8b, 0xf5, 0xcd, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x05, 0x62, 0x72, 0x65, 0x65, 0x64,
	0x18, 0xf4, 0xb2, 0xe9, 0x2c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x65, 0x65, 0x64,
	0x12, 0x12, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0xff, 0xf1, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x61, 0x67, 0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x65, 0x64, 0x65, 0x6e, 0x72, 0x65, 0x69, 0x63, 0x68, 0x2f, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x64, 0x72, 0x69, 0x76, 0x65, 0x6e, 0x2d, 0x64,
	0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x3b,
	0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_cat_proto_rawDescOnce sync.Once
	file_models_cat_proto_rawDescData = file_models_cat_proto_rawDesc
)

func file_models_cat_proto_rawDescGZIP() []byte {
	file_models_cat_proto_rawDescOnce.Do(func() {
		file_models_cat_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_cat_proto_rawDescData)
	})
	return file_models_cat_proto_rawDescData
}

var file_models_cat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_cat_proto_goTypes = []interface{}{
	(*Cat)(nil), // 0: grpc.Cat
}
var file_models_cat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_cat_proto_init() }
func file_models_cat_proto_init() {
	if File_models_cat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_cat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_cat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_cat_proto_goTypes,
		DependencyIndexes: file_models_cat_proto_depIdxs,
		MessageInfos:      file_models_cat_proto_msgTypes,
	}.Build()
	File_models_cat_proto = out.File
	file_models_cat_proto_rawDesc = nil
	file_models_cat_proto_goTypes = nil
	file_models_cat_proto_depIdxs = nil
}
