/*
 * Pets API
 *
 * A simple API to manage pets
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
)

// DogsAPIService is a service that implements the logic for the DogsAPIServicer
// This service should implement the business logic for every endpoint for the DogsAPI API.
// Include any external packages or services that will be required by this service.
type DogsAPIService struct {
}

// NewDogsAPIService creates a default api service
func NewDogsAPIService() DogsAPIServicer {
	return &DogsAPIService{}
}

// GetDogs - Get a list of all dogs
func (s *DogsAPIService) GetDogs(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetDogs with the required logic for this service method.
	// Add api_dogs_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Dog{}) or use other options such as http.Ok ...
	return Response(200, []Dog{
		{
			Id:    "7448d5c9-4e3a-4500-a018-fc25763dd3a4",
			Name:  "Fido",
			Age:   3,
			Breed: "Labrador",
		},
		{
			Id:    "7448d5c9-4e3a-4500-a018-fc25763dd3a5",
			Name:  "Sparky",
			Age:   2,
			Breed: "Labrador",
		},
	}), nil

	// return Response(http.StatusNotImplemented, nil), errors.New("GetDogs method not implemented")
}
