/*
 * Pets API
 *
 * A simple API to manage pets
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	api "github.com/edenreich/definition-driven-development/go"
)

func main() {
	log.Printf("Server started")

	CatsAPIService := api.NewCatsAPIService()
	CatsAPIController := api.NewCatsAPIController(CatsAPIService)

	DogsAPIService := api.NewDogsAPIService()
	DogsAPIController := api.NewDogsAPIController(DogsAPIService)

	router := api.NewRouter(CatsAPIController, DogsAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
