/*
 * Cat API
 *
 * A simple API to manage cats
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/edenreich/definition-driven-development/go"
)

func main() {
	log.Printf("Server started")

	CatsAPIService := openapi.NewCatsAPIService()
	CatsAPIController := openapi.NewCatsAPIController(CatsAPIService)

	router := openapi.NewRouter(CatsAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
