
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Validate OpenAPI Specification
      run: make openapi ARGS='validate -i pets_api.yaml'

    - name: Validate Dirty Workspace
      run: |
        make generate
        git diff --exit-code -- ':!http/api/README.md'

    - name: Test
      run: make test

    # - name: Package HTTP API
    #   run: make package-http-api

    # - name: Package gRPC API
    #   run: make package-grpc-api
